#!/usr/bin/env bash
# Regenerate xsdata-pydantic bindings from the v2 XSD schema.
#
# Usage:
#   ./generate_bindings.sh              # regenerate v2 bindings
#   ./generate_bindings.sh --gen-patches  # regenerate patch files from current committed bindings
#
# Post-generation patches live in packages/aces-amf-lib/patches/.
# Each patch is a standard unified diff applied with `patch --fuzz=2`.
# See patches/README.md for details on what each patch does and why.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
LIB_SRC="$REPO_ROOT/packages/aces-amf-lib/src"
SCHEMA_DIR="$LIB_SRC/aces_amf_lib/data/amf-schema"
PATCHES_DIR="$REPO_ROOT/packages/aces-amf-lib/patches"

# Prefer the project venv xsdata (has cli extras) over any system-level install
if [[ -x "$REPO_ROOT/.venv/bin/xsdata" ]]; then
    XSDATA="$(realpath "$REPO_ROOT/.venv/bin/xsdata")"
elif command -v xsdata &>/dev/null; then
    XSDATA="$(realpath "$(command -v xsdata)")"
else
    echo "ERROR: xsdata not found. Install with: uv pip install 'xsdata[cli]'" >&2
    exit 1
fi

generate() {
    local version="$1"
    local schema="$SCHEMA_DIR/$version/acesMetadataFile.xsd"
    local outdir="$LIB_SRC/aces_amf_lib/amf_$version"
    local package="aces_amf_lib.amf_$version"

    if [[ ! -f "$schema" ]]; then
        echo "ERROR: Schema not found: $schema" >&2
        exit 1
    fi

    echo "Generating $package from $schema ..."

    # Generate into a temp directory to avoid import side-effects.
    local tmpdir
    tmpdir="$(mktemp -d)"
    trap "rm -rf '$tmpdir'" RETURN

    (cd "$tmpdir" && "$XSDATA" generate \
        --output pydantic \
        --package "$package" \
        --include-header \
        "$schema") || true

    # Replace only the versioned subpackage, never the parent __init__.py
    if [[ -d "$tmpdir/aces_amf_lib/amf_$version" ]]; then
        rm -rf "$outdir"
        mv "$tmpdir/aces_amf_lib/amf_$version" "$outdir"
    else
        echo "ERROR: Expected output not found in temp dir" >&2
        exit 1
    fi

    rm -rf "$tmpdir"
    trap - RETURN

    _apply_patches "$version" "$outdir"

    echo "  -> $outdir"
}

_apply_patches() {
    local version="$1"
    local target_dir="$2"

    for patch_file in "$PATCHES_DIR"/${version}_*.patch; do
        [[ -f "$patch_file" ]] || continue
        echo "  Applying $(basename "$patch_file") ..."
        patch -d "$target_dir" -p0 --fuzz=2 < "$patch_file" || {
            echo "ERROR: $(basename "$patch_file") failed to apply." >&2
            echo "  The xsdata output may have changed. Regenerate patches with:" >&2
            echo "    ./generate_bindings.sh --gen-patches" >&2
            exit 1
        }
    done
}

# --gen-patches: regenerate patch files incrementally from current bindings.
gen_patches() {
    local tmpdir
    tmpdir="$(mktemp -d)"
    trap "rm -rf '$tmpdir'" RETURN

    echo "Generating raw (unpatched) bindings for diffing ..."
    local schema="$SCHEMA_DIR/v2/acesMetadataFile.xsd"
    (cd "$tmpdir" && "$XSDATA" generate \
        --output pydantic \
        --package "aces_amf_lib.amf_v2" \
        --include-header \
        "$schema") || true

    mkdir -p "$PATCHES_DIR"

    local target_dir="$LIB_SRC/aces_amf_lib/amf_v2"
    local raw_dir="$tmpdir/aces_amf_lib/amf_v2"

    local work_dir="$tmpdir/work_v2"
    cp -r "$raw_dir" "$work_dir"

    for patch_file in "$PATCHES_DIR"/v2_*.patch; do
        [[ -f "$patch_file" ]] || continue

        local fname
        fname=$(grep -m1 '^--- ' "$patch_file" | sed 's/^--- //')

        local before="$tmpdir/before_$(basename "$patch_file" .patch)"
        cp "$work_dir/$fname" "$before"

        local after_dir="$tmpdir/after_v2"
        cp -r "$work_dir" "$after_dir"
        if ! patch -d "$after_dir" -p0 --fuzz=2 < "$patch_file" >/dev/null 2>&1; then
            cp "$target_dir/$fname" "$after_dir/$fname"
        fi

        local header
        header=$(sed -n '/^#/p; /^[^#]/q' "$patch_file")

        _write_incremental_patch "$before" "$after_dir/$fname" "$fname" "$header" "$patch_file"

        cp "$after_dir/$fname" "$work_dir/$fname"
        rm -rf "$after_dir"
    done

    echo "Patches written to $PATCHES_DIR"
}

_write_incremental_patch() {
    local before="$1"
    local after="$2"
    local fname="$3"
    local header="$4"
    local output="$5"

    local diff_body
    diff_body=$(diff -u "$before" "$after" | \
        sed "1s|.*|--- ${fname}|; 2s|.*|+++ ${fname}|" | \
        python3 -c "
import re, sys
text = sys.stdin.read()
m = re.search(r'^@@', text, re.MULTILINE)
if not m:
    sys.stdout.write(text)
    sys.exit(0)
hdr = text[:m.start()]
body = text[m.start():]
hunks = re.split(r'(?=^@@ )', body, flags=re.MULTILINE)
ts_re = re.compile(r'\"\"\"This file was generated by xsdata')
def keep(h):
    changed = [l for l in h.splitlines() if l.startswith('+') or l.startswith('-')]
    return any(not ts_re.search(l) for l in changed)
sys.stdout.write(hdr + ''.join(h for h in hunks if not h or keep(h)))
") || true

    {
        if [[ -n "$header" ]]; then
            printf '%s\n\n' "$header"
        fi
        printf '%s\n' "$diff_body"
    } > "$output"

    echo "  Written $(basename "$output")"
}

# --- Main ---

if [[ "${1:-}" == "--gen-patches" ]]; then
    gen_patches
    exit 0
fi

generate "v2"

echo "Done."
