"""This file was generated by xsdata, v26.2, on 2026-03-24 22:19:27

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

__NAMESPACE__ = "urn:ASC:CDL:v1.01"


class ColorCorrectionBase(BaseModel):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)
    any_element: None | object = field(
        default=None,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        },
    )


class ColorCorrectionBaseType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    description: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    input_description: None | str = field(
        default=None,
        metadata={
            "name": "InputDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    viewing_description: None | str = field(
        default=None,
        metadata={
            "name": "ViewingDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )


class ColorNodeBase(BaseModel):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)
    any_element: None | object = field(
        default=None,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        },
    )


class ColorNodeBaseType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    description: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )


class MediaBase(BaseModel):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)
    any_element: None | object = field(
        default=None,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        },
    )


class MediaBaseType(BaseModel):
    pass
    model_config = ConfigDict(defer_build=True)


class ColorCorrectionRefType(ColorCorrectionBaseType):
    model_config = ConfigDict(defer_build=True)
    ref: str = field(
        metadata={
            "type": "Attribute",
        }
    )


class MediaRefType(MediaBaseType):
    model_config = ConfigDict(defer_build=True)
    ref: str = field(
        metadata={
            "type": "Attribute",
        }
    )


class SopnodeType(ColorNodeBaseType):
    class Meta:
        name = "SOPNodeType"

    model_config = ConfigDict(defer_build=True)
    slope: list[float] = field(
        default_factory=list,
        metadata={
            "name": "Slope",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_inclusive": 0.0,
            "length": 3,
            "tokens": True,
        },
    )
    offset: list[float] = field(
        default_factory=list,
        metadata={
            "name": "Offset",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "length": 3,
            "tokens": True,
        },
    )
    power: list[float] = field(
        default_factory=list,
        metadata={
            "name": "Power",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_exclusive": 0.0,
            "length": 3,
            "tokens": True,
        },
    )


class SatNodeType(ColorNodeBaseType):
    model_config = ConfigDict(defer_build=True)
    saturation: float = field(
        metadata={
            "name": "Saturation",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_inclusive": 0.0,
        }
    )


class AscCcXml(ColorCorrectionRefType):
    class Meta:
        name = "ASC_CC_XML"
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class AscSat(SatNodeType):
    class Meta:
        name = "ASC_SAT"
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class AscSop(SopnodeType):
    class Meta:
        name = "ASC_SOP"
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class ColorCorrectionRef(ColorCorrectionRefType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class MediaRef(MediaRefType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class Sopnode(SopnodeType):
    class Meta:
        name = "SOPNode"
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class SatNode(SatNodeType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class ColorCorrectionType(ColorCorrectionBaseType):
    model_config = ConfigDict(defer_build=True)
    asc_sat: list[AscSat] = field(
        default_factory=list,
        metadata={
            "name": "ASC_SAT",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    sat_node: list[SatNode] = field(
        default_factory=list,
        metadata={
            "name": "SatNode",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    asc_sop: list[AscSop] = field(
        default_factory=list,
        metadata={
            "name": "ASC_SOP",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    sopnode: list[Sopnode] = field(
        default_factory=list,
        metadata={
            "name": "SOPNode",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    id: str = field(
        metadata={
            "type": "Attribute",
        }
    )


class ColorCorrection(ColorCorrectionType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class ColorCorrectionCollectionType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    description: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    input_description: None | str = field(
        default=None,
        metadata={
            "name": "InputDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    viewing_description: None | str = field(
        default=None,
        metadata={
            "name": "ViewingDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_correction: list[ColorCorrection] = field(
        default_factory=list,
        metadata={
            "name": "ColorCorrection",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_occurs": 1,
        },
    )


class ColorDecisionType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    description: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    input_description: None | str = field(
        default=None,
        metadata={
            "name": "InputDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    viewing_description: None | str = field(
        default=None,
        metadata={
            "name": "ViewingDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    media_ref: None | MediaRef = field(
        default=None,
        metadata={
            "name": "MediaRef",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_correction: None | ColorCorrection = field(
        default=None,
        metadata={
            "name": "ColorCorrection",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    asc_cc_xml: None | AscCcXml = field(
        default=None,
        metadata={
            "name": "ASC_CC_XML",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_correction_ref: None | ColorCorrectionRef = field(
        default=None,
        metadata={
            "name": "ColorCorrectionRef",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )


class ColorCorrectionCollection(ColorCorrectionCollectionType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class ColorDecision(ColorDecisionType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)


class ColorDecisionListType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    description: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    input_description: None | str = field(
        default=None,
        metadata={
            "name": "InputDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    viewing_description: None | str = field(
        default=None,
        metadata={
            "name": "ViewingDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_decision: list[ColorDecision] = field(
        default_factory=list,
        metadata={
            "name": "ColorDecision",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_occurs": 1,
        },
    )


class ColorDecisionList(ColorDecisionListType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    model_config = ConfigDict(defer_build=True)
