"""This file was generated by xsdata, v26.2, on 2026-03-26 20:04:58

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from decimal import Decimal
from enum import Enum

from pydantic import BaseModel, ConfigDict
from xsdata.models.datatype import XmlDateTime
from xsdata_pydantic.fields import field

from aces_amf_lib.amf.asc_cdl_schema_v1_01 import (
    AscCcXml,
    AscSat,
    AscSop,
    ColorCorrectionRef,
    SatNode,
    Sopnode,
)

__NAMESPACE__ = "urn:ampas:aces:amf:v2.0"


class AuthorType(BaseModel):
    class Meta:
        name = "authorType"

    model_config = ConfigDict(defer_build=True)
    name: str = field(
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        }
    )
    email_address: str = field(
        metadata={
            "name": "emailAddress",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"[^@]+@[^@]+",
        }
    )


class DateTimeType(BaseModel):
    class Meta:
        name = "dateTimeType"

    model_config = ConfigDict(defer_build=True)
    creation_date_time: XmlDateTime = field(
        metadata={
            "name": "creationDateTime",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        }
    )
    modification_date_time: XmlDateTime = field(
        metadata={
            "name": "modificationDateTime",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        }
    )


class EmptyType(BaseModel):
    class Meta:
        name = "emptyType"

    model_config = ConfigDict(defer_build=True)


class HashAlgoType(Enum):
    HTTP_WWW_W3_ORG_2001_04_XMLENC_SHA256 = (
        "http://www.w3.org/2001/04/xmlenc#sha256"
    )
    HTTP_WWW_W3_ORG_2000_09_XMLDSIG_SHA1 = (
        "http://www.w3.org/2000/09/xmldsig#sha1"
    )
    HTTP_WWW_W3_ORG_2001_04_XMLDSIG_MORE_MD5 = (
        "http://www.w3.org/2001/04/xmldsig-more#md5"
    )


class SequenceType(BaseModel):
    class Meta:
        name = "sequenceType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(default="")
    idx: str = field(
        metadata={
            "type": "Attribute",
        }
    )
    min: int = field(
        metadata={
            "type": "Attribute",
        }
    )
    max: int = field(
        metadata={
            "type": "Attribute",
        }
    )


class VersionType(BaseModel):
    class Meta:
        name = "versionType"

    model_config = ConfigDict(defer_build=True)
    major_version: int = field(
        metadata={
            "name": "majorVersion",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "min_inclusive": 0,
            "max_inclusive": 9,
            "total_digits": 1,
        }
    )
    minor_version: int = field(
        metadata={
            "name": "minorVersion",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "min_inclusive": 0,
            "max_inclusive": 9,
            "total_digits": 1,
        }
    )
    patch_version: int = field(
        metadata={
            "name": "patchVersion",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "min_inclusive": 0,
            "max_inclusive": 9,
            "total_digits": 1,
        }
    )


class ClipIdType(BaseModel):
    class Meta:
        name = "clipIdType"

    model_config = ConfigDict(defer_build=True)
    clip_name: str = field(
        metadata={
            "name": "clipName",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        }
    )
    sequence: None | SequenceType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )


class HashType(BaseModel):
    class Meta:
        name = "hashType"

    model_config = ConfigDict(defer_build=True)
    value: bytes = field(
        default=b"",
        metadata={
            "format": "base64",
        },
    )
    algorithm: HashAlgoType = field(
        metadata={
            "type": "Attribute",
        }
    )


class InfoType(BaseModel):
    class Meta:
        name = "infoType"

    model_config = ConfigDict(defer_build=True)
    description: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    author: list[AuthorType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    date_time: DateTimeType = field(
        metadata={
            "name": "dateTime",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        }
    )
    uuid: str = field(
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        }
    )


class PipelineInfoType(InfoType):
    class Meta:
        name = "pipelineInfoType"

    model_config = ConfigDict(defer_build=True)
    system_version: VersionType = field(
        metadata={
            "name": "systemVersion",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        }
    )


class TransformType(BaseModel):
    class Meta:
        name = "transformType"

    model_config = ConfigDict(defer_build=True)
    description: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    hash: None | HashType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )


class InverseOutputDeviceTransformType(TransformType):
    class Meta:
        name = "inverseOutputDeviceTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(InvODT\.\S+\.\S+\.a\d+\.v\d+|InvODT\.Academy\.\S+\.a\d+\.\d+\.\d+)",
        },
    )


class InverseOutputTransformType(TransformType):
    class Meta:
        name = "inverseOutputTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(InvRRTODT\.\S+\.\S+\.a\d+\.v\d+|InvRRTODT\.Academy\.\S+\.a\d+\.\d+\.\d+)|urn:ampas:aces:transformId:v2.0:InvOutput\.\S+\.\S+\.a\d+\.v\d+",
        },
    )


class InverseReferenceRenderingTransformType(TransformType):
    class Meta:
        name = "inverseReferenceRenderingTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:InvRRT\.a\d+\.\d+\.\d+",
        },
    )


class OutputDeviceTransformType(TransformType):
    class Meta:
        name = "outputDeviceTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(ODT\.\S+\.\S+\.a\d+\.v\d+|ODT\.Academy\.\S+\.a\d+\.\d+\.\d+)",
        },
    )


class ReferenceRenderingTransformType(TransformType):
    class Meta:
        name = "referenceRenderingTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:RRT\.a\d+\.\d+\.\d+",
        },
    )


class WorkingSpaceTransformType(TransformType):
    class Meta:
        name = "workingSpaceTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(ACEScsc\.\S+\.\S+\.a\d+\.v\d+|ACEScsc\.Academy\.\S+\.a\d+\.\d+\.\d+)|urn:ampas:aces:transformId:v2.0:CSC\.\S+\.\S+\.a\d+\.v\d+",
        },
    )


class CdlWorkingSpaceType(BaseModel):
    class Meta:
        name = "cdlWorkingSpaceType"

    model_config = ConfigDict(defer_build=True)
    to_cdl_working_space: None | WorkingSpaceTransformType = field(
        default=None,
        metadata={
            "name": "toCdlWorkingSpace",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    from_cdl_working_space: WorkingSpaceTransformType = field(
        metadata={
            "name": "fromCdlWorkingSpace",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        }
    )


class InputTransformType(TransformType):
    class Meta:
        name = "inputTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(IDT\.\S+\.\S+\.a\d+\.v\d+|ACEScsc\.\S+\.a\d+\.\d+\.\d+)|urn:ampas:aces:transformId:v2.0:(Input\.\S+\.\S+\.a\d+\.v\d+|CSC\.\S+\.a\d+\.v\d+)",
        },
    )
    inverse_output_transform: None | InverseOutputTransformType = field(
        default=None,
        metadata={
            "name": "inverseOutputTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    inverse_output_device_transform: (
        None | InverseOutputDeviceTransformType
    ) = field(
        default=None,
        metadata={
            "name": "inverseOutputDeviceTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    inverse_reference_rendering_transform: (
        None | InverseReferenceRenderingTransformType
    ) = field(
        default=None,
        metadata={
            "name": "inverseReferenceRenderingTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    applied: bool = field(
        metadata={
            "type": "Attribute",
        }
    )


class OutputTransformType(TransformType):
    class Meta:
        name = "outputTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(RRTODT\.\S+\.\S+\.a\d+\.v\d+|RRTODT\.Academy\.\S+\.a\d+\.\d+\.\d+)|urn:ampas:aces:transformId:v2.0:Output\.\S+\.\S+\.a\d+\.v\d+",
        },
    )
    reference_rendering_transform: None | ReferenceRenderingTransformType = (
        field(
            default=None,
            metadata={
                "name": "referenceRenderingTransform",
                "type": "Element",
                "namespace": "urn:ampas:aces:amf:v2.0",
            },
        )
    )
    output_device_transform: None | OutputDeviceTransformType = field(
        default=None,
        metadata={
            "name": "outputDeviceTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    applied: bool = field(
        metadata={
            "type": "Attribute",
        }
    )


class LookTransformType(TransformType):
    class Meta:
        name = "lookTransformType"

    model_config = ConfigDict(defer_build=True)
    uuid: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    transform_id: None | str = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(LMT\.\S+\.\S+\.a\d+\.v\d+|LMT\.Academy\.\S+\.a\d+\.v?\d+\.\d+)|urn:ampas:aces:transformId:v2.0:Look\.\S+\.\S+\.a\d+\.v\d+",
        },
    )
    cdl_working_space: None | CdlWorkingSpaceType = field(
        default=None,
        metadata={
            "name": "cdlWorkingSpace",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    asc_sop: None | AscSop = field(
        default=None,
        metadata={
            "name": "ASC_SOP",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    sopnode: None | Sopnode = field(
        default=None,
        metadata={
            "name": "SOPNode",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    asc_sat: None | AscSat = field(
        default=None,
        metadata={
            "name": "ASC_SAT",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    sat_node: None | SatNode = field(
        default=None,
        metadata={
            "name": "SatNode",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    asc_cc_xml: None | AscCcXml = field(
        default=None,
        metadata={
            "name": "ASC_CC_XML",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_correction_ref: None | ColorCorrectionRef = field(
        default=None,
        metadata={
            "name": "ColorCorrectionRef",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    applied: bool = field(
        metadata={
            "type": "Attribute",
        }
    )


class PipelineType(BaseModel):
    class Meta:
        name = "pipelineType"

    model_config = ConfigDict(defer_build=True)
    pipeline_info: PipelineInfoType = field(
        metadata={
            "name": "pipelineInfo",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        }
    )
    input_transform: None | InputTransformType = field(
        default=None,
        metadata={
            "name": "inputTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )
    working_location_or_look_transform: list[EmptyType | LookTransformType] = (
        field(
            default_factory=list,
            metadata={
                "type": "Elements",
                "choices": (
                    {
                        "name": "workingLocation",
                        "type": EmptyType,
                        "namespace": "urn:ampas:aces:amf:v2.0",
                    },
                    {
                        "name": "lookTransform",
                        "type": LookTransformType,
                        "namespace": "urn:ampas:aces:amf:v2.0",
                    },
                ),
            },
        )
    )
    output_transform: None | OutputTransformType = field(
        default=None,
        metadata={
            "name": "outputTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v2.0",
        },
    )


class AcesMetadataFile(BaseModel):
    class Meta:
        name = "acesMetadataFile"
        namespace = "urn:ampas:aces:amf:v2.0"

    model_config = ConfigDict(defer_build=True)
    amf_info: InfoType = field(
        metadata={
            "name": "amfInfo",
            "type": "Element",
        }
    )
    clip_id: None | ClipIdType = field(
        default=None,
        metadata={
            "name": "clipId",
            "type": "Element",
        },
    )
    pipeline: PipelineType = field(
        metadata={
            "type": "Element",
        }
    )
    archived_pipeline: list[PipelineType] = field(
        default_factory=list,
        metadata={
            "name": "archivedPipeline",
            "type": "Element",
        },
    )
    version: Decimal = field(
        const=True,
        default=Decimal("2.0"),
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


# --- Post-generation additions (applied by generate_bindings.sh) ---


def _pipeline_get_look_transforms(self) -> list["LookTransformType"]:
    """Read-only filtered view: only LookTransformType items from the
    compound working_location_or_look_transform field."""
    return [
        x
        for x in self.working_location_or_look_transform
        if isinstance(x, LookTransformType)
    ]


PipelineType.look_transforms = property(_pipeline_get_look_transforms)

WorkingLocationType = EmptyType


# --- Post-generation: transform type placement validators ---
# Enforces that transform_id URN prefixes match their container type.
# Uses TransformURN.parse() from aces_common for centralized URN parsing.
# Prefixes are from the v2 XSD (accepts both v1.5 and v2.0 URNs).

from aces_common.types import TransformURN as _TransformURN
from aces_common.constants import (
    V2_INPUT_TRANSFORM_PREFIXES as _INPUT_PFX,
    V2_OUTPUT_TRANSFORM_PREFIXES as _OUTPUT_PFX,
    V2_LOOK_TRANSFORM_PREFIXES as _LOOK_PFX,
    V2_CSC_TRANSFORM_PREFIXES as _CSC_PFX,
)


def _check_transform_type_prefix(
    transform_id: str | None, allowed: frozenset[str], label: str
) -> None:
    """Validate that a transform_id URN prefix is allowed for the given container."""
    if transform_id is None:
        return
    parsed = _TransformURN.parse(transform_id)
    if parsed and parsed.transform_type not in allowed:
        raise ValueError(
            f"Transform ID '{transform_id}' has type '{parsed.transform_type}' "
            f"which is not valid for {label}. "
            f"Allowed: {sorted(allowed)}"
        )


def _wrap_init_with_type_check(cls, allowed: frozenset[str], label: str) -> None:
    """Wrap a Pydantic model's __init__ to validate transform_id placement."""
    original_init = cls.__init__

    def __init__(self, *args, **kwargs):
        original_init(self, *args, **kwargs)
        _check_transform_type_prefix(self.transform_id, allowed, label)

    cls.__init__ = __init__


# Top-level transform containers — these are what users directly construct.
_wrap_init_with_type_check(InputTransformType, _INPUT_PFX, "InputTransform")
_wrap_init_with_type_check(OutputTransformType, _OUTPUT_PFX, "OutputTransform")
_wrap_init_with_type_check(LookTransformType, _LOOK_PFX, "LookTransform")
_wrap_init_with_type_check(WorkingSpaceTransformType, _CSC_PFX, "WorkingSpaceTransform")

# Sub-transform types (RRT, ODT, InverseRRT, InverseODT, InverseOutput) are
# intentionally NOT validated here. Real-world v1 AMF files often place RRTODT
# in ReferenceRenderingTransform slots, violating the strict XSD pattern.
# The v1->v2 upgrade path needs to load these files without error.
