"""This file was generated by xsdata, v24.5, on 2024-05-29 12:05:01

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import List, Optional

from xsdata.models.datatype import XmlDateTime

from .asc_cdl_schema_v1_01 import (
    AscCcXml,
    AscSat,
    AscSop,
    ColorCorrectionRef,
    SatNode,
    Sopnode,
)

__NAMESPACE__ = "urn:ampas:aces:amf:v1.0"


@dataclass
class AuthorType:
    class Meta:
        name = "authorType"

    name: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )
    email_address: Optional[str] = field(
        default=None,
        metadata={
            "name": "emailAddress",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
            "pattern": r"[^@]+@[^\.]+\..+",
        },
    )


@dataclass
class DateTimeType:
    class Meta:
        name = "dateTimeType"

    creation_date_time: Optional[XmlDateTime] = field(
        default=None,
        metadata={
            "name": "creationDateTime",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )
    modification_date_time: Optional[XmlDateTime] = field(
        default=None,
        metadata={
            "name": "modificationDateTime",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )


class HashAlgoType(Enum):
    HTTP_WWW_W3_ORG_2001_04_XMLENC_SHA256 = "http://www.w3.org/2001/04/xmlenc#sha256"
    HTTP_WWW_W3_ORG_2000_09_XMLDSIG_SHA1 = "http://www.w3.org/2000/09/xmldsig#sha1"
    HTTP_WWW_W3_ORG_2001_04_XMLDSIG_MORE_MD5 = "http://www.w3.org/2001/04/xmldsig-more#md5"


@dataclass
class SequenceType:
    class Meta:
        name = "sequenceType"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    idx: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    min: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    max: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class VersionType:
    class Meta:
        name = "versionType"

    major_version: Optional[int] = field(
        default=None,
        metadata={
            "name": "majorVersion",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 9,
            "total_digits": 1,
        },
    )
    minor_version: Optional[int] = field(
        default=None,
        metadata={
            "name": "minorVersion",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 9,
            "total_digits": 1,
        },
    )
    patch_version: Optional[int] = field(
        default=None,
        metadata={
            "name": "patchVersion",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 9,
            "total_digits": 1,
        },
    )


@dataclass
class ClipIdType:
    class Meta:
        name = "clipIdType"

    clip_name: Optional[str] = field(
        default=None,
        metadata={
            "name": "clipName",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )
    sequence: Optional[SequenceType] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )


@dataclass
class HashType:
    class Meta:
        name = "hashType"

    value: Optional[bytes] = field(
        default=None,
        metadata={
            "required": True,
            "format": "base64",
        },
    )
    algorithm: Optional[HashAlgoType] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class InfoType:
    class Meta:
        name = "infoType"

    description: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    author: List[AuthorType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    date_time: Optional[DateTimeType] = field(
        default=None,
        metadata={
            "name": "dateTime",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )
    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )


@dataclass
class PipelineInfoType(InfoType):
    class Meta:
        name = "pipelineInfoType"

    system_version: Optional[VersionType] = field(
        default=None,
        metadata={
            "name": "systemVersion",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )


@dataclass
class TransformType:
    class Meta:
        name = "transformType"

    description: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    hash: Optional[HashType] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )


@dataclass
class InverseOutputDeviceTransformType(TransformType):
    class Meta:
        name = "inverseOutputDeviceTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(InvODT\.\S+\.\S+\.a\d+\.v\d+|InvODT\.Academy\.\S+\.a\d+\.\d+\.\d+)",
        },
    )


@dataclass
class InverseOutputTransformType(TransformType):
    class Meta:
        name = "inverseOutputTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(InvRRTODT\.\S+\.\S+\.a\d+\.v\d+|InvRRTODT\.Academy\.\S+\.a\d+\.\d+\.\d+)",
        },
    )


@dataclass
class InverseReferenceRenderingTransformType(TransformType):
    class Meta:
        name = "inverseReferenceRenderingTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:InvRRT\.a\d+\.\d+\.\d+",
        },
    )


@dataclass
class OutputDeviceTransformType(TransformType):
    class Meta:
        name = "outputDeviceTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(ODT\.\S+\.\S+\.a\d+\.v\d+|ODT\.Academy\.\S+\.a\d+\.\d+\.\d+)",
        },
    )


@dataclass
class ReferenceRenderingTransformType(TransformType):
    class Meta:
        name = "referenceRenderingTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:RRT\.a\d+\.\d+\.\d+",
        },
    )


@dataclass
class WorkingSpaceTransformType(TransformType):
    class Meta:
        name = "workingSpaceTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(ACEScsc\.\S+\.\S+\.a\d+\.v\d+|ACEScsc\.Academy\.\S+\.a\d+\.\d+\.\d+)",
        },
    )


@dataclass
class CdlWorkingSpaceType:
    class Meta:
        name = "cdlWorkingSpaceType"

    to_cdl_working_space: Optional[WorkingSpaceTransformType] = field(
        default=None,
        metadata={
            "name": "toCdlWorkingSpace",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    from_cdl_working_space: Optional[WorkingSpaceTransformType] = field(
        default=None,
        metadata={
            "name": "fromCdlWorkingSpace",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )


@dataclass
class InputTransformType(TransformType):
    class Meta:
        name = "inputTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:IDT\.\S+\.\S+\.a\d+\.v\d+",
        },
    )
    inverse_output_transform: Optional[InverseOutputTransformType] = field(
        default=None,
        metadata={
            "name": "inverseOutputTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    inverse_output_device_transform: Optional[InverseOutputDeviceTransformType] = field(
        default=None,
        metadata={
            "name": "inverseOutputDeviceTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    inverse_reference_rendering_transform: Optional[InverseReferenceRenderingTransformType] = field(
        default=None,
        metadata={
            "name": "inverseReferenceRenderingTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    applied: Optional[bool] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class OutputTransformType(TransformType):
    class Meta:
        name = "outputTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(RRTODT\.\S+\.\S+\.a\d+\.v\d+|RRTODT\.Academy\.\S+\.a\d+\.\d+\.\d+)",
        },
    )
    reference_rendering_transform: Optional[ReferenceRenderingTransformType] = field(
        default=None,
        metadata={
            "name": "referenceRenderingTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    output_device_transform: Optional[OutputDeviceTransformType] = field(
        default=None,
        metadata={
            "name": "outputDeviceTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )


@dataclass
class LookTransformType(TransformType):
    class Meta:
        name = "lookTransformType"

    uuid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        },
    )
    file: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    transform_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "transformId",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "pattern": r"urn:ampas:aces:transformId:v1.5:(LMT\.\S+\.\S+\.a\d+\.v\d+|LMT\.Academy\.\S+\.a\d+\.\d+\.\d+)",
        },
    )
    cdl_working_space: Optional[CdlWorkingSpaceType] = field(
        default=None,
        metadata={
            "name": "cdlWorkingSpace",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    asc_sop: Optional[AscSop] = field(
        default=None,
        metadata={
            "name": "ASC_SOP",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    sopnode: Optional[Sopnode] = field(
        default=None,
        metadata={
            "name": "SOPNode",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    asc_sat: Optional[AscSat] = field(
        default=None,
        metadata={
            "name": "ASC_SAT",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    sat_node: Optional[SatNode] = field(
        default=None,
        metadata={
            "name": "SatNode",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    asc_cc_xml: Optional[AscCcXml] = field(
        default=None,
        metadata={
            "name": "ASC_CC_XML",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_correction_ref: Optional[ColorCorrectionRef] = field(
        default=None,
        metadata={
            "name": "ColorCorrectionRef",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    applied: Optional[bool] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class PipelineType:
    class Meta:
        name = "pipelineType"

    pipeline_info: Optional[PipelineInfoType] = field(
        default=None,
        metadata={
            "name": "pipelineInfo",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )
    input_transform: Optional[InputTransformType] = field(
        default=None,
        metadata={
            "name": "inputTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    look_transform: List[LookTransformType] = field(
        default_factory=list,
        metadata={
            "name": "lookTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
        },
    )
    output_transform: Optional[OutputTransformType] = field(
        default=None,
        metadata={
            "name": "outputTransform",
            "type": "Element",
            "namespace": "urn:ampas:aces:amf:v1.0",
            "required": True,
        },
    )


@dataclass
class AcesMetadataFile:
    class Meta:
        name = "acesMetadataFile"
        namespace = "urn:ampas:aces:amf:v1.0"

    amf_info: Optional[InfoType] = field(
        default=None,
        metadata={
            "name": "amfInfo",
            "type": "Element",
            "required": True,
        },
    )
    clip_id: Optional[ClipIdType] = field(
        default=None,
        metadata={
            "name": "clipId",
            "type": "Element",
        },
    )
    pipeline: Optional[PipelineType] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    archived_pipeline: List[PipelineType] = field(
        default_factory=list,
        metadata={
            "name": "archivedPipeline",
            "type": "Element",
        },
    )
    version: Decimal = field(
        init=False,
        default=Decimal("1.0"),
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
