"""This file was generated by xsdata, v24.5, on 2024-05-29 12:05:01

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import List, Optional

__NAMESPACE__ = "urn:ASC:CDL:v1.01"


@dataclass
class ColorCorrectionBase:
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    any_element: Optional[object] = field(
        default=None,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        },
    )


@dataclass
class ColorCorrectionBaseType:
    description: List[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    input_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "InputDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    viewing_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "ViewingDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )


@dataclass
class ColorNodeBase:
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    any_element: Optional[object] = field(
        default=None,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        },
    )


@dataclass
class ColorNodeBaseType:
    description: List[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )


@dataclass
class MediaBase:
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"

    any_element: Optional[object] = field(
        default=None,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        },
    )


@dataclass
class MediaBaseType:
    pass


@dataclass
class ColorCorrectionRefType(ColorCorrectionBaseType):
    ref: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class MediaRefType(MediaBaseType):
    ref: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class SopnodeType(ColorNodeBaseType):
    class Meta:
        name = "SOPNodeType"

    slope: List[float] = field(
        default_factory=list,
        metadata={
            "name": "Slope",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_inclusive": 0.0,
            "length": 3,
            "tokens": True,
        },
    )
    offset: List[float] = field(
        default_factory=list,
        metadata={
            "name": "Offset",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "length": 3,
            "tokens": True,
        },
    )
    power: List[float] = field(
        default_factory=list,
        metadata={
            "name": "Power",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_exclusive": 0.0,
            "length": 3,
            "tokens": True,
        },
    )


@dataclass
class SatNodeType(ColorNodeBaseType):
    saturation: Optional[float] = field(
        default=None,
        metadata={
            "name": "Saturation",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "required": True,
            "min_inclusive": 0.0,
        },
    )


@dataclass
class AscCcXml(ColorCorrectionRefType):
    class Meta:
        name = "ASC_CC_XML"
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class AscSat(SatNodeType):
    class Meta:
        name = "ASC_SAT"
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class AscSop(SopnodeType):
    class Meta:
        name = "ASC_SOP"
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class ColorCorrectionRef(ColorCorrectionRefType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class MediaRef(MediaRefType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class Sopnode(SopnodeType):
    class Meta:
        name = "SOPNode"
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class SatNode(SatNodeType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class ColorCorrectionType(ColorCorrectionBaseType):
    asc_sat: List[AscSat] = field(
        default_factory=list,
        metadata={
            "name": "ASC_SAT",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    sat_node: List[SatNode] = field(
        default_factory=list,
        metadata={
            "name": "SatNode",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    asc_sop: List[AscSop] = field(
        default_factory=list,
        metadata={
            "name": "ASC_SOP",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    sopnode: List[Sopnode] = field(
        default_factory=list,
        metadata={
            "name": "SOPNode",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    id: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class ColorCorrection(ColorCorrectionType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class ColorCorrectionCollectionType:
    description: List[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    input_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "InputDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    viewing_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "ViewingDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_correction: List[ColorCorrection] = field(
        default_factory=list,
        metadata={
            "name": "ColorCorrection",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_occurs": 1,
        },
    )


@dataclass
class ColorDecisionType:
    description: List[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    input_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "InputDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    viewing_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "ViewingDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    media_ref: Optional[MediaRef] = field(
        default=None,
        metadata={
            "name": "MediaRef",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_correction: Optional[ColorCorrection] = field(
        default=None,
        metadata={
            "name": "ColorCorrection",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    asc_cc_xml: Optional[AscCcXml] = field(
        default=None,
        metadata={
            "name": "ASC_CC_XML",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_correction_ref: Optional[ColorCorrectionRef] = field(
        default=None,
        metadata={
            "name": "ColorCorrectionRef",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )


@dataclass
class ColorCorrectionCollection(ColorCorrectionCollectionType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class ColorDecision(ColorDecisionType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"


@dataclass
class ColorDecisionListType:
    description: List[str] = field(
        default_factory=list,
        metadata={
            "name": "Description",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    input_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "InputDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    viewing_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "ViewingDescription",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
        },
    )
    color_decision: List[ColorDecision] = field(
        default_factory=list,
        metadata={
            "name": "ColorDecision",
            "type": "Element",
            "namespace": "urn:ASC:CDL:v1.01",
            "min_occurs": 1,
        },
    )


@dataclass
class ColorDecisionList(ColorDecisionListType):
    class Meta:
        namespace = "urn:ASC:CDL:v1.01"
