"""This file was generated by xsdata, v24.5, on 2024-05-29 12:05:01

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import List, Optional

__NAMESPACE__ = "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/"


@dataclass
class UserTextType:
    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    language: str = field(
        default="en",
        metadata={
            "type": "Attribute",
        },
    )


class CurrentModeToken(Enum):
    AC = "AC"
    DC = "DC"


class CurrentUnitsToken(Enum):
    AMPS = "amps"
    MILLIAMPS = "milliamps"


class DeviceIdentifierPolyTypeIdtype(Enum):
    DEVICE_UID = "DeviceUID"
    CERT_THUMBPRINT = "CertThumbprint"


@dataclass
class DeviceTypeType:
    class Meta:
        name = "deviceTypeType"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    scope: str = field(
        default="http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/#device-type-tokens",
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class ScopedTokenType:
    class Meta:
        name = "scopedTokenType"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    scope: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


class TemperatureUnitsToken(Enum):
    CELSIUS = "celsius"
    FAHRENHEIT = "fahrenheit"
    KELVIN = "kelvin"


class TimeUnitToken(Enum):
    WEEK = "week"
    DAY = "day"
    HOUR = "hour"
    MINUTE = "minute"
    SECOND = "second"
    MILLISECOND = "millisecond"
    MICROSECOND = "microsecond"


@dataclass
class VersionInfoListType:
    class Meta:
        name = "versionInfoListType"

    name: List[str] = field(
        default_factory=list,
        metadata={
            "name": "Name",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "min_occurs": 1,
        },
    )
    value: List[str] = field(
        default_factory=list,
        metadata={
            "name": "Value",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "min_occurs": 1,
        },
    )


class VoltageUnitsToken(Enum):
    VOLTS = "volts"
    MILLIVOLTS = "millivolts"
    MICROVOLTS = "microvolts"


@dataclass
class CurrentType:
    class Meta:
        name = "currentType"

    value: Optional[Decimal] = field(
        default=None,
        metadata={
            "required": True,
        },
    )
    units: Optional[CurrentUnitsToken] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    mode: Optional[CurrentModeToken] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class DeviceIdentifierPolyType:
    class Meta:
        name = "deviceIdentifierPolyType"

    value: str = field(
        default="",
        metadata={
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
            "format": "base64",
        },
    )
    idtype: Optional[DeviceIdentifierPolyTypeIdtype] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class DurationType:
    class Meta:
        name = "durationType"

    value: Optional[Decimal] = field(
        default=None,
        metadata={
            "required": True,
        },
    )
    units: Optional[TimeUnitToken] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class NamedParmType:
    class Meta:
        name = "namedParmType"

    name: Optional[ScopedTokenType] = field(
        default=None,
        metadata={
            "name": "Name",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "required": True,
        },
    )
    value: Optional[object] = field(
        default=None,
        metadata={
            "name": "Value",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )


@dataclass
class RateType:
    class Meta:
        name = "rateType"

    value: List[int] = field(
        default_factory=list,
        metadata={
            "tokens": True,
        },
    )
    eventscope: str = field(
        default="http://www.smpte-ra.org/schemas/433/2008/dcmlTypes#rate-scope-tokens",
        metadata={
            "type": "Attribute",
        },
    )
    event: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    period: Optional[TimeUnitToken] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class TemperatureType:
    class Meta:
        name = "temperatureType"

    value: Optional[Decimal] = field(
        default=None,
        metadata={
            "required": True,
        },
    )
    units: Optional[TemperatureUnitsToken] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class VoltageType:
    class Meta:
        name = "voltageType"

    value: Optional[Decimal] = field(
        default=None,
        metadata={
            "required": True,
        },
    )
    units: Optional[VoltageUnitsToken] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    mode: Optional[CurrentModeToken] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class DeviceDescriptionType:
    class Meta:
        name = "deviceDescriptionType"

    device_identifier: Optional[DeviceIdentifierPolyType] = field(
        default=None,
        metadata={
            "name": "DeviceIdentifier",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "required": True,
        },
    )
    device_type_id: Optional[DeviceTypeType] = field(
        default=None,
        metadata={
            "name": "DeviceTypeID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "required": True,
        },
    )
    device_subsystem_type_id: Optional[DeviceTypeType] = field(
        default=None,
        metadata={
            "name": "DeviceSubsystemTypeID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    additional_id: Optional[object] = field(
        default=None,
        metadata={
            "name": "AdditionalID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    device_serial: Optional[str] = field(
        default=None,
        metadata={
            "name": "DeviceSerial",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "required": True,
        },
    )
    manufacturer_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "ManufacturerID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    manufacturer_cert_id: Optional[bytes] = field(
        default=None,
        metadata={
            "name": "ManufacturerCertID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "format": "base64",
        },
    )
    device_cert_id: Optional[bytes] = field(
        default=None,
        metadata={
            "name": "DeviceCertID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "format": "base64",
        },
    )
    manufacturer_name: Optional[str] = field(
        default=None,
        metadata={
            "name": "ManufacturerName",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    device_name: Optional[str] = field(
        default=None,
        metadata={
            "name": "DeviceName",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    model_number: Optional[str] = field(
        default=None,
        metadata={
            "name": "ModelNumber",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    version_info: Optional[VersionInfoListType] = field(
        default=None,
        metadata={
            "name": "VersionInfo",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "required": True,
        },
    )
    device_comment: Optional[UserTextType] = field(
        default=None,
        metadata={
            "name": "DeviceComment",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )


@dataclass
class DeviceIdentifierListType:
    class Meta:
        name = "deviceIdentifierListType"

    primary_id: Optional[DeviceIdentifierPolyType] = field(
        default=None,
        metadata={
            "name": "PrimaryID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "required": True,
        },
    )
    secondary_id: Optional[DeviceIdentifierPolyType] = field(
        default=None,
        metadata={
            "name": "SecondaryID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )


@dataclass
class ParameterListType:
    class Meta:
        name = "parameterListType"

    parameter: List[NamedParmType] = field(
        default_factory=list,
        metadata={
            "name": "Parameter",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "min_occurs": 1,
        },
    )


@dataclass
class DeviceDescription(DeviceDescriptionType):
    class Meta:
        namespace = "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/"


@dataclass
class DeviceIdentifierList(DeviceIdentifierListType):
    class Meta:
        namespace = "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/"
