"""This file was generated by xsdata, v26.2, on 2026-03-17 11:54:42

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from decimal import Decimal
from enum import Enum

from pydantic import BaseModel, ConfigDict
from xsdata_pydantic.fields import field

__NAMESPACE__ = "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/"


class UserTextType(BaseModel):
    model_config = ConfigDict(defer_build=True)
    value: str = field(default="")
    language: str = field(
        default="en",
        metadata={
            "type": "Attribute",
        },
    )


class CurrentModeToken(Enum):
    AC = "AC"
    DC = "DC"


class CurrentUnitsToken(Enum):
    AMPS = "amps"
    MILLIAMPS = "milliamps"


class DeviceIdentifierPolyTypeIdtype(Enum):
    DEVICE_UID = "DeviceUID"
    CERT_THUMBPRINT = "CertThumbprint"


class DeviceTypeType(BaseModel):
    class Meta:
        name = "deviceTypeType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(default="")
    scope: str = field(
        default="http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/#device-type-tokens",
        metadata={
            "type": "Attribute",
        },
    )


class ScopedTokenType(BaseModel):
    class Meta:
        name = "scopedTokenType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(default="")
    scope: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


class TemperatureUnitsToken(Enum):
    CELSIUS = "celsius"
    FAHRENHEIT = "fahrenheit"
    KELVIN = "kelvin"


class TimeUnitToken(Enum):
    WEEK = "week"
    DAY = "day"
    HOUR = "hour"
    MINUTE = "minute"
    SECOND = "second"
    MILLISECOND = "millisecond"
    MICROSECOND = "microsecond"


class VersionInfoListType(BaseModel):
    class Meta:
        name = "versionInfoListType"

    model_config = ConfigDict(defer_build=True)
    name: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Name",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "min_occurs": 1,
        },
    )
    value: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Value",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "min_occurs": 1,
        },
    )


class VoltageUnitsToken(Enum):
    VOLTS = "volts"
    MILLIVOLTS = "millivolts"
    MICROVOLTS = "microvolts"


class CurrentType(BaseModel):
    class Meta:
        name = "currentType"

    model_config = ConfigDict(defer_build=True)
    value: Decimal = field()
    units: CurrentUnitsToken = field(
        metadata={
            "type": "Attribute",
        }
    )
    mode: CurrentModeToken = field(
        metadata={
            "type": "Attribute",
        }
    )


class DeviceIdentifierPolyType(BaseModel):
    class Meta:
        name = "deviceIdentifierPolyType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(
        default="",
        metadata={
            "pattern": r"urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
            "format": "base64",
        },
    )
    idtype: DeviceIdentifierPolyTypeIdtype = field(
        metadata={
            "type": "Attribute",
        }
    )


class DurationType(BaseModel):
    class Meta:
        name = "durationType"

    model_config = ConfigDict(defer_build=True)
    value: Decimal = field()
    units: TimeUnitToken = field(
        metadata={
            "type": "Attribute",
        }
    )


class NamedParmType(BaseModel):
    class Meta:
        name = "namedParmType"

    model_config = ConfigDict(defer_build=True)
    name: ScopedTokenType = field(
        metadata={
            "name": "Name",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        }
    )
    value: None | object = field(
        default=None,
        metadata={
            "name": "Value",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )


class RateType(BaseModel):
    class Meta:
        name = "rateType"

    model_config = ConfigDict(defer_build=True)
    value: list[int] = field(
        default_factory=list,
        metadata={
            "tokens": True,
        },
    )
    eventscope: str = field(
        default="http://www.smpte-ra.org/schemas/433/2008/dcmlTypes#rate-scope-tokens",
        metadata={
            "type": "Attribute",
        },
    )
    event: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    period: TimeUnitToken = field(
        metadata={
            "type": "Attribute",
        }
    )


class TemperatureType(BaseModel):
    class Meta:
        name = "temperatureType"

    model_config = ConfigDict(defer_build=True)
    value: Decimal = field()
    units: TemperatureUnitsToken = field(
        metadata={
            "type": "Attribute",
        }
    )


class VoltageType(BaseModel):
    class Meta:
        name = "voltageType"

    model_config = ConfigDict(defer_build=True)
    value: Decimal = field()
    units: VoltageUnitsToken = field(
        metadata={
            "type": "Attribute",
        }
    )
    mode: CurrentModeToken = field(
        metadata={
            "type": "Attribute",
        }
    )


class DeviceDescriptionType(BaseModel):
    class Meta:
        name = "deviceDescriptionType"

    model_config = ConfigDict(defer_build=True)
    device_identifier: DeviceIdentifierPolyType = field(
        metadata={
            "name": "DeviceIdentifier",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        }
    )
    device_type_id: DeviceTypeType = field(
        metadata={
            "name": "DeviceTypeID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        }
    )
    device_subsystem_type_id: None | DeviceTypeType = field(
        default=None,
        metadata={
            "name": "DeviceSubsystemTypeID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    additional_id: None | object = field(
        default=None,
        metadata={
            "name": "AdditionalID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    device_serial: str = field(
        metadata={
            "name": "DeviceSerial",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        }
    )
    manufacturer_id: None | str = field(
        default=None,
        metadata={
            "name": "ManufacturerID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    manufacturer_cert_id: None | bytes = field(
        default=None,
        metadata={
            "name": "ManufacturerCertID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "format": "base64",
        },
    )
    device_cert_id: None | bytes = field(
        default=None,
        metadata={
            "name": "DeviceCertID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "format": "base64",
        },
    )
    manufacturer_name: None | str = field(
        default=None,
        metadata={
            "name": "ManufacturerName",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    device_name: None | str = field(
        default=None,
        metadata={
            "name": "DeviceName",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    model_number: None | str = field(
        default=None,
        metadata={
            "name": "ModelNumber",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )
    version_info: VersionInfoListType = field(
        metadata={
            "name": "VersionInfo",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        }
    )
    device_comment: None | UserTextType = field(
        default=None,
        metadata={
            "name": "DeviceComment",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )


class DeviceIdentifierListType(BaseModel):
    class Meta:
        name = "deviceIdentifierListType"

    model_config = ConfigDict(defer_build=True)
    primary_id: DeviceIdentifierPolyType = field(
        metadata={
            "name": "PrimaryID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        }
    )
    secondary_id: None | DeviceIdentifierPolyType = field(
        default=None,
        metadata={
            "name": "SecondaryID",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
        },
    )


class ParameterListType(BaseModel):
    class Meta:
        name = "parameterListType"

    model_config = ConfigDict(defer_build=True)
    parameter: list[NamedParmType] = field(
        default_factory=list,
        metadata={
            "name": "Parameter",
            "type": "Element",
            "namespace": "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/",
            "min_occurs": 1,
        },
    )


class DeviceDescription(DeviceDescriptionType):
    class Meta:
        namespace = "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/"

    model_config = ConfigDict(defer_build=True)


class DeviceIdentifierList(DeviceIdentifierListType):
    class Meta:
        namespace = "http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/"

    model_config = ConfigDict(defer_build=True)
